"""
Generates a .docx export that:
- Preserves original question order
- Inserts answer below each question
- Includes citations
"""

import json, os, uuid
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from models import QRun, QAnswer
from typing import List


def export_to_docx(run: QRun, answers: List[QAnswer]) -> str:
    doc = Document()

    # ── Title ──────────────────────────────────────────────────────────────
    title = doc.add_heading(f"Questionnaire: {run.name}", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"Generated by StreamHive RAG Assistant")
    doc.add_paragraph("")

    # ── Answers ────────────────────────────────────────────────────────────
    for ans in answers:
        # Question
        q_para = doc.add_paragraph()
        q_run = q_para.add_run(f"Q{ans.question_id}. {ans.question_text}")
        q_run.bold = True
        q_run.font.size = Pt(11)
        q_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        # Answer
        a_para = doc.add_paragraph()
        a_label = a_para.add_run("Answer: ")
        a_label.bold = True
        a_label.font.color.rgb = RGBColor(0x0F, 0x3C, 0x78)
        a_para.add_run(ans.answer_text)

        # Citations
        try:
            citations = json.loads(ans.citations) if ans.citations else []
        except Exception:
            citations = []

        if citations:
            c_para = doc.add_paragraph()
            c_label = c_para.add_run("Citations: ")
            c_label.italic = True
            c_label.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            sources = ", ".join(set(c["source"] for c in citations))
            c_para.add_run(sources).italic = True

            # Evidence snippets
            for c in citations:
                snippet_para = doc.add_paragraph(style="List Bullet")
                r = snippet_para.add_run(f"[{c['source']}] ")
                r.bold = True
                r.font.size = Pt(9)
                snippet_para.add_run(c["snippet"] + "…").font.size = Pt(9)

        doc.add_paragraph("")  # spacer

    out_dir = "exports"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"run_{run.id}_{uuid.uuid4().hex[:6]}.docx")
    doc.save(out_path)
    return out_path